# Generated by Django 4.1.3 on 2022-11-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('second_name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('postcode', models.IntegerField()),
                ('purpose', models.CharField(max_length=200)),
                ('amount', models.BigIntegerField()),
                ('asset_cost', models.BigIntegerField()),
                ('tentor', models.BigIntegerField()),
                ('tentormonthly', models.BigIntegerField()),
                ('photo', models.ImageField(default='', upload_to='form/')),
                ('document', models.ImageField(default='', upload_to='form/')),
            ],
        ),
    ]
